
services:
  jenkins:
    image: jenkins-docker-controller:latest
    container_name: jenkins
    ports:
      - 9091:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: on-failure
volumes:
  jenkins_home: