pipeline {
    agent any

    tools {
        nodejs 'node-24'
    }

    stages {
        stage('Tools-node') {
            steps {
                sh 'node -v'
                sh 'npm -v'
            }
        }
    }
}